# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentiment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\"9\n\x15\x41nalyzeCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"k\n\x16\x41nalyzeCommentResponse\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x11\n\tsentiment\x18\x02 \x01(\t\x12\x15\n\roriginal_text\x18\x03 \x01(\t\x12\x13\n\x0b\x61nalyzed_at\x18\x04 \x01(\x03\x32i\n\x10SentimentService\x12U\n\x0e\x41nalyzeComment\x12 .sentiment.AnalyzeCommentRequest\x1a!.sentiment.AnalyzeCommentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZECOMMENTREQUEST']._serialized_start=30
  _globals['_ANALYZECOMMENTREQUEST']._serialized_end=87
  _globals['_ANALYZECOMMENTRESPONSE']._serialized_start=89
  _globals['_ANALYZECOMMENTRESPONSE']._serialized_end=196
  _globals['_SENTIMENTSERVICE']._serialized_start=198
  _globals['_SENTIMENTSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
